const ON_BULK_PUBLISH_UPDATION = 'ON_BULK_PUBLISH_UPDATION';
const ON_BULK_PUBLISH_UPDATION_PAGES = 'ON_BULK_PUBLISH_UPDATION_PAGES';
const ON_BULK_PUBLISH_UPDATION_ERROR = 'ON_BULK_PUBLISH_UPDATION_ERROR';
const ON_BULK_PUBLISH_TABS = 'ON_BULK_PUBLISH_TABS';
const UPDATE_PAGES_STATE_ON_BULK_PUBLISH = 'UPDATE_PAGES_STATE_ON_BULK_PUBLISH';

export default {
  ON_BULK_PUBLISH_UPDATION,
  ON_BULK_PUBLISH_UPDATION_ERROR,
  ON_BULK_PUBLISH_TABS,
  ON_BULK_PUBLISH_UPDATION_PAGES,
  UPDATE_PAGES_STATE_ON_BULK_PUBLISH,
};
