const ADD_VERSION_REQUEST = 'ADD_VERSION_REQUEST';
const ON_VERSION_ADDED = 'ON_VERSION_ADDED';
const ON_VERSION_ADDED_ERROR = 'ON_VERSION_ADDED_ERROR';
const UPDATE_VERSION_REQUEST = 'UPDATE_VERSION_REQUEST';
const ON_VERSION_UPDATED = 'ON_VERSION_UPDATED';
const ON_VERSION_UPDATED_ERROR = 'ON_VERSION_UPDATED_ERROR';
const ON_VERSION_DUPLICATED = 'ON_VERSION_DUPLICATED';
const ON_PARENTPAGE_VERSION_ADDED = 'ON_PARENTPAGE_VERSION_ADDED';
const ON_DEFAULT_VERSION = 'ON_DEFAULT_VERSION';
const ON_DEFAULT_VERSION_ERROR = 'ON_DEFAULT_VERSION_ERROR';

export default {
  ADD_VERSION_REQUEST,
  ON_VERSION_ADDED,
  ON_VERSION_ADDED_ERROR,
  UPDATE_VERSION_REQUEST,
  ON_VERSION_UPDATED,
  ON_VERSION_UPDATED_ERROR,
  ON_VERSION_DUPLICATED,
  ON_PARENTPAGE_VERSION_ADDED,
  ON_DEFAULT_VERSION,
  ON_DEFAULT_VERSION_ERROR,
};
