const ON_OPEN_MODAL = 'ON_OPEN_MODAL';
const ON_CLOSE_MODAL = 'ON_CLOSE_MODAL';
const ON_INSTALL_MODAL = 'ON_INSTALL_MODAL';
const ON_PUBLISH_DOC = 'ON_PUBLISH_DOC';
const ON_CURL_SLIDER_OPEN = 'ON_CURL_SLIDER_OPEN';
export default {
  ON_OPEN_MODAL,
  ON_CLOSE_MODAL,
  ON_INSTALL_MODAL,
  ON_PUBLISH_DOC,
  ON_CURL_SLIDER_OPEN,
};
