const ON_PAGES_FETCHED = 'ON_PAGES_FETCHED';
const ON_PAGES_FETCHED_ERROR = 'ON_PAGES_FETCHED_ERROR';
const ON_PAGE_FETCHED = 'ON_PAGE_FETCHED';
const ON_PAGE_FETCHED_ERROR = 'ON_PAGE_FETCHED_ERROR';
const ADD_PAGE_REQUEST = 'ADD_PAGE_REQUEST';
const ON_PAGE_ADDED = 'ON_PAGE_ADDED';
const ON_PAGE_ADDED_ERROR = 'ON_PAGE_ADDED_ERROR';
const ADD_GROUP_PAGE_REQUEST = 'ADD_GROUP_PAGE_REQUEST';
const ON_GROUP_PAGE_ADDED = 'ON_GROUP_PAGE_ADDED';
const ON_GROUP_PAGE_ADDED_ERROR = 'ON_GROUP_PAGE_ADDED_ERROR';
const UPDATE_PAGE_REQUEST = 'UPDATE_PAGE_REQUEST';
const ON_PAGE_UPDATED = 'ON_PAGE_UPDATED';
const ON_PAGE_UPDATED_ERROR = 'ON_PAGE_UPDATED_ERROR';
const DELETE_PAGE_REQUEST = 'DELETE_PAGE_REQUEST';
const ON_PAGE_DELETED = 'ON_PAGE_DELETED';
const ON_PAGE_DELETED_ERROR = 'ON_PAGE_DELETED_ERROR';
const ON_PAGE_DUPLICATED = 'ON_PAGE_DUPLICATED';
const ON_PAGES_ORDER_UPDATED = 'ON_PAGES_ORDER_UPDATED:';
const ON_PAGES_ORDER_UPDATED_ERROR = 'ON_PAGES_ORDER_UPDATED_ERROR';
const ADD_PARENT_PAGE_REQUEST = 'ADD_PARENT_PAGE_REQUEST';
const ON_PARENT_PAGE_ADDED = 'ON_PARENT_PAGE_ADDED';
const UPDATE_CONTENT_OF_PAGE = 'UPDATE_CONTENT_OF_PAGE';
const UPDATE_PAGE_DATA = 'UPDATE_PAGE_DATA';
const ADD_VERSION_REQUEST = 'ADD_VERSION_REQUEST';
const ON_PARENTPAGE_VERSION_ADDED = 'ON_PARENTPAGE_VERSION_ADDED';
const ADD_CHILD_IN_PARENT = 'ADD_CHILD_IN_PARENT';
const UPDATE_NAME_OF_PAGE = 'UPDATE_NAME_OF_PAGE';
const UPDATE_ENDPOINT_REQUEST = 'UPDATE_ENDPOINT_REQUEST';
const ON_ENDPOINT_UPDATED = 'ON_ENDPOINT_UPDATED';
const ON_ENDPOINT_DELETED = 'ON_ENDPOINT_DELETED';
const DELETE_ENDPOINT_REQUEST = 'DELETE_ENDPOINT_REQUEST';
const ON_ENDPOINT_DELETED_ERROR = 'ON_ENDPOINT_DELETED_ERROR';
const ON_ENDPOINT_DUPLICATED = 'ON_ENDPOINT_DUPLICATED';
const ON_DRAG_DROP = 'ON_DRAG_DROP';
const ADD_OLD_URL = 'ADD_OLD_URL';
const DELETE_OLD_URL = 'DELETE_OLD_URL';
const ON_PAGE_RENAME = 'ON_PAGE_RENAME';

export default {
  ON_PAGES_FETCHED,
  ON_PAGES_FETCHED_ERROR,
  ON_PAGE_FETCHED,
  ON_PAGE_FETCHED_ERROR,
  ADD_PAGE_REQUEST,
  ON_PAGE_ADDED,
  ON_PARENT_PAGE_ADDED,
  ON_PAGE_ADDED_ERROR,
  ADD_GROUP_PAGE_REQUEST,
  ADD_PARENT_PAGE_REQUEST,
  UPDATE_CONTENT_OF_PAGE,
  ON_GROUP_PAGE_ADDED,
  ON_GROUP_PAGE_ADDED_ERROR,
  UPDATE_PAGE_REQUEST,
  ON_PAGE_UPDATED,
  ON_PAGE_UPDATED_ERROR,
  DELETE_PAGE_REQUEST,
  ON_PAGE_DELETED,
  ON_PAGE_DELETED_ERROR,
  ON_PAGE_DUPLICATED,
  ON_PAGES_ORDER_UPDATED,
  ON_PAGES_ORDER_UPDATED_ERROR,
  UPDATE_PAGE_DATA,
  ON_PARENTPAGE_VERSION_ADDED,
  ADD_VERSION_REQUEST,
  ADD_CHILD_IN_PARENT,
  UPDATE_NAME_OF_PAGE,
  UPDATE_ENDPOINT_REQUEST,
  ON_ENDPOINT_UPDATED,
  ON_ENDPOINT_DELETED,
  DELETE_ENDPOINT_REQUEST,
  ON_ENDPOINT_DELETED_ERROR,
  ON_ENDPOINT_DUPLICATED,
  ON_DRAG_DROP,
  ADD_OLD_URL,
  DELETE_OLD_URL,
  ON_PAGE_RENAME,
};
