const ON_PUBLIC_ENDPOINTS_FETCHED = 'ON_PUBLIC_ENDPOINTS_FETCHED';
const ON_PUBLIC_ENDPOINTS_FETCHED_ERROR = 'ON_PUBLIC_ENDPOINTS_FETCHED_ERROR';
const ON_ENDPOINT_STATE_SUCCESS = 'ON_ENDPOINT_STATE_SUCCESS';
const ON_ENDPOINT_STATE_ERROR = 'ON_ENDPOINT_STATE_ERROR';
const ON_PAGE_STATE_SUCCESS = 'ON_PAGE_STATE_SUCCESS';
const ON_PAGE_STATE_ERROR = 'ON_PAGE_STATE_ERROR';
const ON_REJECT_ENDPOINT_SUCCESS = 'ON_REJECT_ENDPOINT_SUCCESS';
const ON_REJECT_ENDPOINT_ERROR = 'ON_REJECT_ENDPOINT_ERROR';
const ON_DRAFT_ENDPOINT_SUCCESS = 'ON_DRAFT_ENDPOINT_SUCCESS';
const ON_DRAFT_ENDPOINT_ERROR = 'ON_DRAFT_ENDPOINT_ERROR';
const UPDATE_ENDPOINT_REQUEST = 'UPDATE_ENDPOINT_REQUEST';
export default {
  ON_PUBLIC_ENDPOINTS_FETCHED,
  ON_PUBLIC_ENDPOINTS_FETCHED_ERROR,
  ON_ENDPOINT_STATE_SUCCESS,
  ON_ENDPOINT_STATE_ERROR,
  ON_PAGE_STATE_SUCCESS,
  ON_PAGE_STATE_ERROR,
  ON_REJECT_ENDPOINT_SUCCESS,
  ON_REJECT_ENDPOINT_ERROR,
  ON_DRAFT_ENDPOINT_SUCCESS,
  ON_DRAFT_ENDPOINT_ERROR,
  UPDATE_ENDPOINT_REQUEST,
};
