const ON_ENVIRONMENTS_FETCHED = 'ON_ENVIRONMENTS_FETCHED';
const ON_ENVIRONMENTS_FETCHED_ERROR = 'ON_ENVIRONMENTS_FETCHED_ERROR';
const ADD_ENVIRONMENT_REQUEST = 'ADD_ENVIRONMENT_REQUEST';
const ON_ENVIRONMENT_ADDED = 'ON_ENVIRONMENT_ADDED';
const ON_ENVIRONMENT_ADDED_ERROR = 'ON_ENVIRONMENT_ADDED_ERROR';
const UPDATE_ENVIRONMENT_REQUEST = 'UPDATE_ENVIRONMENT_REQUEST';
const ON_ENVIRONMENT_UPDATED = 'ON_ENVIRONMENT_UPDATED';
const ON_ENVIRONMENT_UPDATED_ERROR = 'ON_ENVIRONMENT_UPDATED_ERROR';
const DELETE_ENVIRONMENT_REQUEST = 'DELETE_ENVIRONMENT_REQUEST';
const ON_ENVIRONMENT_DELETED = 'ON_ENVIRONMENT_DELETED';
const ON_ENVIRONMENT_DELETED_ERROR = 'ON_ENVIRONMENT_DELETED_ERROR';
const SET_ENVIRONMENT_ID = 'SET_ENVIRONMENT_ID';
const ON_ENVIRONMENT_IMPORTED = 'ON_ENVIRONMENT_IMPORTED';

export default {
  ON_ENVIRONMENTS_FETCHED,
  ON_ENVIRONMENTS_FETCHED_ERROR,
  ADD_ENVIRONMENT_REQUEST,
  ON_ENVIRONMENT_ADDED,
  ON_ENVIRONMENT_ADDED_ERROR,
  UPDATE_ENVIRONMENT_REQUEST,
  ON_ENVIRONMENT_UPDATED,
  ON_ENVIRONMENT_UPDATED_ERROR,
  DELETE_ENVIRONMENT_REQUEST,
  ON_ENVIRONMENT_DELETED,
  ON_ENVIRONMENT_DELETED_ERROR,
  SET_ENVIRONMENT_ID,
  ON_ENVIRONMENT_IMPORTED,
};
