const ADD_IS_EXPANDED = 'ADD_IS_EXPANDED';
const DEFAULT_VERSION_ID = 'DEFAULT_VERSION_ID';
const UPDATE_FOR_ISPUBLISH = 'UPDATE_FOR_ISPUBLISH';
const UDPATE_ENDPOINT_CHECK_STATUS = 'UDPATE_ENDPOINT_CHECK_STATUS';
const UPDATE_ALL_ENDPOINTS_CHECK_STATUS = 'UPDATE_ALL_ENDPOINTS_CHECK_STATUS';
const UPDATE_MODE = 'UPDATE_MODE';

export default {
  ADD_IS_EXPANDED,
  DEFAULT_VERSION_ID,
  UPDATE_FOR_ISPUBLISH,
  UDPATE_ENDPOINT_CHECK_STATUS,
  UPDATE_MODE,
  UPDATE_ALL_ENDPOINTS_CHECK_STATUS,
};
