const ADD_NEW_TAB = 'ADD_NEW_TAB';
const CLOSE_TAB = 'CLOSE_TAB';
const UPDATE_TAB = 'UPDATE_TAB';
const UPDATE_TAB_DRAFT = 'UPDATE_TAB_DRAFT';
const OPEN_IN_NEW_TAB = 'OPEN_IN_NEW_TAB';
const SET_ACTIVE_TAB_ID = 'SET_ACTIVE_TAB_ID';
const SET_TABS_ORDER = 'SET_TABS_ORDER';
const FETCH_TABS_FROM_REDUX = 'FETCH_TABS_FROM_REDUX';
const REPLACE_TAB = 'REPLACE_TAB';
const CLOSE_ALL_TABS = 'CLOSE_ALL_TABS';
const REPLACE_TAB_ID = 'REPLACE_TAB_ID';
const UPDATE_PRE_POST_SCRIPT = 'UPDATE_PRE_POST_SCRIPT';
const SET_INTROSPECTION_SCHEMA = 'SET_INTROSPECTION_SCHEMA';
const SET_PAGE_TYPE = 'SET_PAGE_TYPE';
const FETCH_PAGE_CONTENT_REQUEST = 'FETCH_PAGE_CONTENT_REQUEST';
const FETCH_PAGE_CONTENT_SUCCESS = 'FETCH_PAGE_CONTENT_SUCCESS';
const FETCH_PAGE_CONTENT_FAILURE = 'FETCH_PAGE_CONTENT_FAILURE';
const UPDATE_DRAFT_CONTENT = 'UPDATE_DRAFT_CONTENT';
const UPDATE_NEW_TAB_NAME = 'UPDATE_NEW_TAB_NAME';
const DELETE_TAB_NAME = 'DELETE_TAB_NAME';
const SET_TAB_MODIFIED = 'SET_TAB_MODIFIED';

export default {
  ADD_NEW_TAB,
  CLOSE_TAB,
  UPDATE_TAB,
  UPDATE_TAB_DRAFT,
  OPEN_IN_NEW_TAB,
  SET_ACTIVE_TAB_ID,
  SET_TABS_ORDER,
  FETCH_TABS_FROM_REDUX,
  REPLACE_TAB,
  CLOSE_ALL_TABS,
  REPLACE_TAB_ID,
  UPDATE_PRE_POST_SCRIPT,
  SET_INTROSPECTION_SCHEMA,
  SET_PAGE_TYPE,
  FETCH_PAGE_CONTENT_FAILURE,
  FETCH_PAGE_CONTENT_REQUEST,
  FETCH_PAGE_CONTENT_SUCCESS,
  UPDATE_DRAFT_CONTENT,
  UPDATE_NEW_TAB_NAME,
  DELETE_TAB_NAME,
  SET_TAB_MODIFIED,
};
