const ON_COLLECTIONS_FETCHED = 'ON_COLLECTIONS_FETCHED';
const ON_COLLECTIONS_FETCHED_ERROR = 'ON_COLLECTIONS_FETCHED_ERROR';
const ADD_COLLECTION_REQUEST = 'ADD_COLLECTION_REQUEST';
const ON_COLLECTION_ADDED = 'ON_COLLECTION_ADDED';
const ON_COLLECTION_ADDED_ERROR = 'ON_COLLECTION_ADDED_ERROR';
const UPDATE_COLLECTION_REQUEST = 'UPDATE_COLLECTION_REQUEST';
const ON_COLLECTION_UPDATED = 'ON_COLLECTION_UPDATED';
const ON_COLLECTION_UPDATED_ERROR = 'ON_COLLECTION_UPDATED_ERROR';
const DELETE_COLLECTION_REQUEST = 'DELETE_COLLECTION_REQUEST';
const ON_COLLECTION_DELETED = 'ON_COLLECTION_DELETED';
const ON_COLLECTION_DELETED_ERROR = 'ON_COLLECTION_DELETED_ERROR';
const ON_COLLECTION_DUPLICATED = 'ON_COLLECTION_DUPLICATED';
const ON_COLLECTION_DUPLICATED_ERROR = 'ON_COLLECTION_DUPLICATED_ERROR';
const ADD_CUSTOM_DOMAIN = 'ADD_CUSTOM_DOMAIN';
const IMPORT_COLLECTION_REQUEST = 'IMPORT_COLLECTION_REQUEST';
const ON_COLLECTION_IMPORTED = 'ON_COLLECTION_IMPORTED';
const ON_COLLECTION_IMPORTED_ERROR = 'ON_COLLECTION_IMPORTED_ERROR';

export default {
  ON_COLLECTIONS_FETCHED,
  ON_COLLECTIONS_FETCHED_ERROR,
  ADD_COLLECTION_REQUEST,
  ON_COLLECTION_ADDED,
  ON_COLLECTION_ADDED_ERROR,
  UPDATE_COLLECTION_REQUEST,
  ON_COLLECTION_UPDATED,
  ON_COLLECTION_UPDATED_ERROR,
  DELETE_COLLECTION_REQUEST,
  ON_COLLECTION_DELETED,
  ON_COLLECTION_DELETED_ERROR,
  ON_COLLECTION_DUPLICATED,
  ON_COLLECTION_DUPLICATED_ERROR,
  ADD_CUSTOM_DOMAIN,
  IMPORT_COLLECTION_REQUEST,
  ON_COLLECTION_IMPORTED,
  ON_COLLECTION_IMPORTED_ERROR,
};
