const ON_AUTOMATION_RUN = 'ON_AUTOMATION_RUN';
const ON_AUTOMATION_RUN_ERROR = 'ON_AUTOMATION_RUN_ERROR';
const ON_GENERATE_DESCRIPTION = 'ON_GENERATE_DESCRIPTION';
const ON_GENERATE_DESCRIPTION_ERROR = 'ON_GENERATE_DESCRIPTION_ERROR';

export default {
  ON_AUTOMATION_RUN,
  ON_AUTOMATION_RUN_ERROR,
  ON_GENERATE_DESCRIPTION,
  ON_GENERATE_DESCRIPTION_ERROR,
};
