export const CREATE_NEW_PUBLIC_ENVIRONMENT = ' CREATE_NEW_PUBLIC_ENVIRONMENT ';
export const UPDATE_PUBLIC_ENV = 'UPDATE_PUBLIC_ENV';
export const DELETE_SELECTED_INDEX = 'DELETE_SELECTED_INDEX';
export const DELETE_ENTIRE_PUBLIC_ENV = 'DELETE_ENTIRE_PUBLIC_ENV';
