const ON_ENDPOINT_UPDATED_ERROR = 'ON_ENDPOINT_UPDATED_ERROR';
const DELETE_ENDPOINT_REQUEST = 'DELETE_ENDPOINT_REQUEST';
const ON_ENDPOINT_DELETED = 'ON_ENDPOINT_DELETED';
const ON_ENDPOINT_DELETED_ERROR = 'ON_ENDPOINT_DELETED_ERROR';
const MOVE_ENDPOINT_REQUEST = 'MOVE_ENDPOINT_REQUEST';
const MOVE_ENDPOINT_SUCCESS = 'MOVE_ENDPOINT_SUCCESS';
const ON_ENDPOINTS_ORDER_UPDATED = 'ON_ENDPOINTS_ORDER_UPDATED';
const ON_ENDPOINTS_ORDER_UPDATED_ERROR = 'ON_ENDPOINTS_ORDER_UPDATED_ERROR';

export default {
  ON_ENDPOINT_UPDATED_ERROR,
  DELETE_ENDPOINT_REQUEST,
  ON_ENDPOINT_DELETED,
  ON_ENDPOINT_DELETED_ERROR,
  MOVE_ENDPOINT_SUCCESS,
  MOVE_ENDPOINT_REQUEST,
  ON_ENDPOINTS_ORDER_UPDATED,
  ON_ENDPOINTS_ORDER_UPDATED_ERROR,
};
